# Generated by Django 3.1.7 on 2021-03-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zid_code',
            new_name='zip_code',
        ),
    ]
